INSERT INTO BOOKS 
(BOOKID,AUTHOR,AVAILABLECOPIES,BOOKNAME,TOTALCOPIES)
values('B1212','Ross Suarez',0,'History of Amazon Valley',2);
INSERT INTO BOOKS 
(BOOKID,AUTHOR,AVAILABLECOPIES,BOOKNAME,TOTALCOPIES)
values('B4232','H S Parkmay',5,'Language Fundamentals',5);